### ISSUE TITLE
Suggestion to Add a License to the Repository

### ISSUE THREAD

**Issue by va-li** [jakarto3d/py-OCamCalib#5]
Hello Mr. Vazquez!

First and foremost, thank you for open-sourcing this wonderful Python implementation of OCamCalib. It's been incredibly helpful for fisheye camera calibration and I truly appreciate the effort you've put into it.

I've noticed that the repository doesn't currently have an overall license. Some files have the GNU GPLv2 header, yet not all. Specifically the following files are without a liscense header:

- [src/pyocamcalib/core/linear_estimation.py](https://github.com/jakarto3d/py-OCamCalib/blob/9f1ec470a2f020d761fe0a63698ffbff7454b32d/src/pyocamcalib/core/linear_estimation.py)
- [src/pyocamcalib/modelling/utils.py](https://github.com/jakarto3d/py-OCamCalib/blob/9f1ec470a2f020d761fe0a63698ffbff7454b32d/src/pyocamcalib/modelling/utils.py)
- [src/pyocamcalib/script/calibration_script.py](https://github.com/jakarto3d/py-OCamCalib/blob/9f1ec470a2f020d761fe0a63698ffbff7454b32d/src/pyocamcalib/script/calibration_script.py)
- [src/pyocamcalib/script/projection_conversion_script.py](https://github.com/jakarto3d/py-OCamCalib/blob/9f1ec470a2f020d761fe0a63698ffbff7454b32d/src/pyocamcalib/script/projection_conversion_script.py)

I am using your work in an academic institution for research and we would like to open source the code, modifications to it and results responsibly. Having a clear license on all files necessary to perform the calibration would guide me on how best to do this.

Would you consider adding a license to these files or possibly the entire repository?

Thank you once again for your work!

Best regards,

Valentin Bauer

**Comment by HugoVazquez-x** [comment]
Hello Mr. Bauer,

Thank you for your words. I'm really pleased to hear that this repository is helpful to you!

I've added headers for the 4 missing files and a general license for the repository. I hope this helps you.

Best,
Hugo

**Comment by va-li** [comment]
Wow, this was super fast, thank you very much!

Best regards,
Valentin
